import { RandomUtil } from '@/utils';

import { createDefaultHysteriaInboundSettings, createDefaultVlessInboundSettings } from '@/lib/xray/inbound-defaults';
import { createHysteriaTlsSettingsWithDefaultCert, createTlsSettingsWithDefaultCert } from '@/lib/xray/inbound-tls-defaults';
import { HysteriaStreamSettingsSchema } from '@/schemas/protocols/stream/hysteria';
import { RealityStreamSettingsSchema } from '@/schemas/protocols/security/reality';
import { TcpStreamSettingsSchema } from '@/schemas/protocols/stream/tcp';
import { GrpcStreamSettingsSchema } from '@/schemas/protocols/stream/grpc';
import { XHttpStreamSettingsSchema } from '@/schemas/protocols/stream/xhttp';

/*
 * Inbound connection templates for the "Create from template" flow. Each
 * builder returns a partial form value set layered on top of the plain add
 * defaults (port, tag, sniffing stay generated by the form). Values that must
 * be unique per user (UUID, port, path) are never baked in.
 */
export interface TemplateContext {
  domain?: string;
  certFile?: string;
  keyFile?: string;
  webDomain?: string;
  publicIp?: string;
  defaultCert?: string;
  defaultKey?: string;
  certSource?: string;
}

export interface InboundTemplate {
  id: string;
  title: string;
  description: string;
  requiresDomain: boolean;
  build: (ctx: TemplateContext) => Record<string, unknown>;
}

const REALITY_TARGET = 'x5media.ru:443';
const REALITY_SNI = 'x5media.ru';
const FIREFOX_UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:151.0) Gecko/20100101 Firefox/151.0';

function buildRealitySettings() {
  return RealityStreamSettingsSchema.parse({
    target: REALITY_TARGET,
    serverNames: [REALITY_SNI],
    settings: { fingerprint: 'firefox', spiderX: '/' },
  });
}

function buildTlsWithDomain(domain: string, certFile: string | undefined, keyFile: string | undefined) {
  const tls = createTlsSettingsWithDefaultCert() as Record<string, unknown>;
  tls.serverName = domain;
  tls.alpn = ['h2', 'http/1.1'];
  const settings = tls.settings && typeof tls.settings === 'object' && !Array.isArray(tls.settings)
    ? { ...(tls.settings as Record<string, unknown>) }
    : {};
  settings.fingerprint = 'firefox';
  tls.settings = settings;
  if (certFile && keyFile) {
    tls.certificates = [{
      useFile: true,
      certificateFile: certFile,
      keyFile,
      certificate: [],
      key: [],
      ocspStapling: 0,
      oneTimeLoading: false,
      usage: 'encipherment',
      buildChain: false,
    }];
  } else {
    tls.certificates = [];
  }
  return tls;
}

function buildRealityStream(settings: unknown) {
  return {
    network: 'tcp',
    security: 'reality',
    tcpSettings: TcpStreamSettingsSchema.parse({ header: { type: 'none' } }),
    realitySettings: settings,
  };
}

export const INBOUND_TEMPLATES: InboundTemplate[] = [
  {
    id: 'vless-tcp-reality',
    title: 'vless + tcp + Reality',
    description: 'Базовая конфигурация для vpn, в некоторых регионах уже не работает',
    requiresDomain: false,
    build() {
      return {
        protocol: 'vless',
        settings: createDefaultVlessInboundSettings(),
        streamSettings: buildRealityStream(buildRealitySettings()),
      };
    },
  },
  {
    id: 'hysteria2-tls',
    title: 'hysteria2 + TLS',
    description: 'quic протокол, в большинстве мест работает (рекомендуется 443 порт)',
    requiresDomain: false,
    build(ctx) {
      const tls = createHysteriaTlsSettingsWithDefaultCert() as Record<string, unknown>;
      const sni = (ctx.webDomain?.trim() || ctx.publicIp || '').trim();
      if (sni) tls.serverName = sni;
      if (ctx.defaultCert && ctx.defaultKey) {
        tls.certificates = [{
          useFile: true,
          certificateFile: ctx.defaultCert,
          keyFile: ctx.defaultKey,
          certificate: [],
          key: [],
          ocspStapling: 0,
          oneTimeLoading: false,
          usage: 'encipherment',
          buildChain: false,
        }];
      } else {
        // An empty certificateFile/keyFile pair makes xray fail with "both
        // file and bytes are empty" — leave no cert entry at all and let the
        // caller warn the user to fill the paths manually.
        tls.certificates = [];
      }
      return {
        protocol: 'hysteria',
        settings: createDefaultHysteriaInboundSettings(),
        streamSettings: {
          network: 'hysteria',
          security: 'tls',
          hysteriaSettings: HysteriaStreamSettingsSchema.parse({
            masquerade: { type: '', dir: '', url: '', rewriteHost: false, insecure: false, content: '', headers: {}, statusCode: 0 },
          }),
          tlsSettings: tls,
          finalmask: {
            tcp: [],
            udp: [{ type: 'salamander', settings: { password: RandomUtil.randomLowerAndNum(16) } }],
          },
        },
      };
    },
  },
  {
    id: 'vless-grpc-reality',
    title: 'vless + gRPC + Reality',
    description: 'Рабочий вариант на сегодняшний день',
    requiresDomain: false,
    build() {
      return {
        protocol: 'vless',
        settings: createDefaultVlessInboundSettings(),
        streamSettings: {
          network: 'grpc',
          security: 'reality',
          grpcSettings: GrpcStreamSettingsSchema.parse({ serviceName: 'gRPC_service', authority: REALITY_SNI }),
          realitySettings: buildRealitySettings(),
        },
      };
    },
  },
  {
    id: 'vless-xhttp-tls',
    title: 'vless + XHTTP + TLS',
    description: 'Максимальное скрытие под сайт, работать должен везде (нужен домен)',
    requiresDomain: true,
    build(ctx) {
      const domain = ctx.domain ?? '';
      return {
        protocol: 'vless',
        settings: createDefaultVlessInboundSettings(),
        streamSettings: {
          network: 'xhttp',
          security: 'tls',
          tlsSettings: buildTlsWithDomain(domain, ctx.certFile, ctx.keyFile),
          xhttpSettings: XHttpStreamSettingsSchema.parse({
            path: '/media/live/',
            host: domain,
            mode: 'packet-up',
            xPaddingBytes: '48-300',
            xPaddingObfsMode: true,
            xPaddingKey: '_rnd',
            xPaddingHeader: 'X_Cache',
            xPaddingMethod: 'tokenish',
            scStreamUpServerSecs: '20-80',
            uplinkHTTPMethod: 'GET',
            headers: {
              Accept: '*/*',
              'Accept-Language': 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7',
              'Accept-Encoding': 'gzip, deflate, br, zstd',
              Origin: `https://${domain}/`,
              Referer: `https://${domain}/`,
              'Sec-Fetch-Dest': 'empty',
              'Sec-Fetch-Mode': 'cors',
              'Sec-Fetch-Site': 'same-origin',
              'User-Agent': FIREFOX_UA,
            },
            scMinPostsIntervalMs: '50-150',
            xmux: {
              maxConcurrency: '',
              maxConnections: '6',
              cMaxReuseTimes: 0,
              hMaxRequestTimes: '1000-2000',
              hMaxReusableSecs: '1800-3600',
              hKeepAlivePeriod: 15,
            },
            enableXmux: true,
          }),
        },
      };
    },
  },
];